version: "3.5"

services: 
    web:
        build: ./app
        container_name: web_api
        ports:
            - 8000:8000
        volumes:
            - ./app:/app
        env_file: 
            ./app/.env
        depends_on: 
            - postgres

    postgres:
        image: postgres:11.7
        container_name: web_database
        ports:
            - 5433:5432
        volumes: 
            - ./postgres:/var/lib/postgresql/data
