# Generated by Django 3.0.5 on 2020-05-16 01:24

import challegen.enuns
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challegen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=challegen.enuns.ChallegenStatusEnun['OPEN'])),
                ('challenged', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_challengeds', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_challegens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
